#! /bin/bash

# Run windows programs from bash.
# Convert all path arguments except the first to Windows paths.
# (Copied from cygwin.bash_aliases)
function w {
    p=
    for ((at=2; at <= $#; at++))
    do
		if [ -e ${!at} ] ; then
			arg="`cygpath --windows --absolute ${!at}`"
		else
			arg="${!at}"
		fi
		p="$p $arg"
    done
    $1 $p &
}

# I'm using python for windows (but not using PYTHONHOME because doing so
# conflicts with our build).
python=$(cygpath $MY_PYTHONHOME/python.exe)

w $python $*
