#! /bin/bash
# vim:set fdm=marker:

# Build the filelist, tag file, and cscope databases
# usage:
#   buildtags.sh [--continuous] cscope-binary lang [directories to search]
#
# example to build C++ in current directory recursively:
#   buildtags.sh --continous cscope cpp
# example for the same but only tags (no filelist or cscope):
#   buildtags.sh tagonly cpp
# example for the same but no cscope:
#   buildtags.sh skip-cscope cpp

# Installing dependents:
#   aptinstall exuberant-ctags cscope
#   pip install pycscope
#   brew install fswatch
#   aptinstall fswatch # (requires universe)

continuous=0
if [ "$1" == "--continuous" ] ; then
    echo Doing continuous build...
    continuous=1
    shift
fi

cscope=$1
if [ $# -lt 1 ] ; then
    # assume plain cscope if we got no input
    cscope=cscope
fi

filetype=$2

search_dirs=.
if [ $# -gt 2 ] ; then
    # search directories passed in

	# ignore cscope and filetype
	shift
	shift
	# use remaining parameters
    search_dirs=$*
fi


if [[ $continuous -eq 1 ]]; then
    if [[ -x "$(command -v fswatch)" ]]; then
        fswatch --print0 $search_dirs | while read -d "" event
        do
            # Ignore vim swap file changes
            if [[ $event == *.*.sw* ]]; then
                echo Ignoring change to file $event
            else
                echo Rebuild tags...
                $0 $cscope $filetype $search_dirs
            fi
        done
    else
        # Only linux seems to have watch support by default.
        while inotifywait --event close_write,moved_to,create --recursive $search_dirs ; do
            $0 $cscope $filetype $search_dirs
        done
    fi
    exit
fi

tagdir=$PWD
tagfile=$tagdir/filelist

# debugging info
#~ echo cscope=$cscope filetype=$filetype tagfile=$tagfile
#~ echo search_dirs=$search_dirs

cd $tagdir

# Use a tempfile to prevent them from appearing in the current directory.
TMPFILE="$(mktemp -t buildtags.XXXXXX)"
trap "rm -f '$TMPFILE'" 0               # EXIT
trap "rm -f '$TMPFILE'; exit 1" 2       # INT
trap "rm -f '$TMPFILE'; exit 1" 1 15    # HUP TERM

# Build filelist	{{{
touch $tagfile
rm $tagfile
if [ "$filetype" == "cpp" ] ; then
    # Probably a big c++ project, so use the simple format
    find $search_dirs -type f \( -iname "*.cpp" -o -iname "*.h" -o -iname "*.inl" \) -print | sort -f >> $tagfile

elif [ "$filetype" == "lua-engine" ] ; then
	# Lua-based engines use C++ and lua.
    find $search_dirs -type d -name examples -prune -o -type f \( -iname "*.cpp" -o -iname "*.h" -o -iname "*.inl" -o -iname "*.lua" \) -print | sort -f >> $tagfile

elif [ "$filetype" == "unreal" ] ; then
	# A big unreal c++ project, so use the simple format. Ignore generated code
	# in the Intermediate folder (a nuisance in plugins that don't have a fixed
	# path format).
    find $search_dirs -type f \( -iname "*.cpp" -o -iname "*.h" -o -iname "*.inl" \) -print | grep -v "Intermediate.Build" | sort -f >> $tagfile

elif [ "$filetype" == "cs" ] ; then
    # C sharp code. don't include examples which are often alongside.
    find $search_dirs -not \( -name "examples" -prune \) -a -not \( -name "obj" -prune \) -a \( -type f -iname "*.cs" -o -iname "*.xaml" \) -print | sort -f >> $tagfile
    # Should try this:
    #find $search_dirs \( -type d -name "examples" -o -name "obj" \) -prune -o \( -type f -iname "*.cs" -o -iname "*.xaml" \) -print | sort -f >> $tagfile

elif [ "$filetype" == "android" ] ; then
    # Android uses java and xml. Assume we're in the source directory
    find $tagdir ../res -type f \( -iname "*.xml" -o -iname "*.java" \) -print | sort -f >> $tagfile

elif [ "$filetype" == "java" ] ; then
    # The only types we're interested in are java
    find $search_dirs -type f -iname "*.java" -print | sort -f >> $tagfile

else
    # Don't know what we are so include anything that's not binary or junk (from vimdoc)
    # DavidAdd: Files: .git tags filelist
    # DavidAdd: Filetypes: pyc out
    # DavidAdd: Folder: v (for virtualenv)
    find $search_dirs \( -name .git -o -name v -o -name .svn -o -name .bzr -o -name tags -o -name filelist -o -wholename ./classes \) -prune -o -not -iregex '.*\.\(pyc\|jar\|gif\|jpg\|class\|exe\|dll\|pdd\|sw[op]\|xls\|doc\|pdf\|zip\|tar\|ico\|ear\|war\|dat\|out\).*' -type f -print | sort -f >> $tagfile

fi

# convert cygwin paths to windows paths
sed -e"s,^/cygdrive/\([[:alpha:]]\)/,\1:/," $tagfile > $TMPFILE
mv $TMPFILE $tagfile
# I used to make a link in the root to each drive letter (/c for c:). With Bash
# on Windows, I can just make a c:/mnt folder with all of the drives in it.
# However, this acts wonky if the local drive isn't c:.
# I'm not doing this here because Bash on Windows tools (ctags) need unix
# paths. Instead, postponed this later so vim only sees Windows paths.
#sed -i -e"s,^//\([[:alpha:]]\)/,\1:/," $tagfile
# }}}

# Build ctags and cscope	{{{
# Fixup the filelist

case $OSTYPE in
	cygwin*)
	# mlcscope needs full paths, so replace the relative path with the fully
	# qualified path
	# TODO: cygwin replaced mlcscope with cscope. Does it still have this problem?
	sed -i -e"s|^\./|$tagdir/|" $tagfile
;;
	*)
	# cscope doesn't seem to need full paths
	# do nothing.
;;
esac

function fix_file_prefix_for_tags_on_win32()
{
    # Vim doesn't understand / as beginning of the path in Windows so it thinks
    # they're relative paths and can't find anything. (I'm using gvim.exe but
    # building tags with Unix subsystem.)
    sed -i -e"s,/mnt/\([[:alpha:]]\)/,\1:/," $1

    # For reference, opposite transformation.
    # sed -e"s,\([[:alpha:]]\):/,/mnt/\1/,"
}

case $filetype in
    cpp|c)
        ctags --c++-kinds=+p --fields=+iaS --extra=+q -L $tagfile
        ;;
    cs)
        # Need namespace kind for inclement.
        # Need fields for tag completion.
        #
        # Using all kinds except:
        #   e  enumerators (enumeration values) -- just jump to enum instead
        #   f  fields -- adds 70% more bytes
        #   l  local variables -- adds 90% more bytes
        #
        # Using minimal field info:
        #   k Kind of tag as a single letter [enabled]
        #   s Scope of tag definition
        #   t Type and name of a variable or typedef as "typeref:" field
        # (excludes f from defaults because it didn't seem useful)
        #
        # Other fields:
        #   a Access (or export) of class members 
        #   f File-restricted scoping
        #   i Inheritance information
        #   K Kind of tag as full name
        #   l Language of source file containing tag
        #   m Implementation information
        #   n Line number of tag definition
        #   S Signature of routine (e.g. prototype or parameter list)
        #   z Include the "kind:" key in kind field
        # 
        # Trying out removing extra because it increases size by 1.2x.
        #
        # .\ctags.exe --extra=+fq --fields=+ianmzS --c#-kinds=cimnp
        #
        ctags --c#-kinds=cismpdngtEf --fields=kst -L $tagfile
        ;;
    lua-engine)
        # ltags makes for better lua tags and doesn't bloat the database with
        # c++.
        # Builds separate lua.tags from cpp tags file. Vim must have:
        #   setlocal tags+=./lua.tags;/
        # (See ~/.vim/bundle/lua-david/after/ftplugin/lua.vim)
        grep lua $tagfile > $tagfile.luaonly
        # The -nv option is no good for us since we declare classes as locals
        # returned from a file. Don't use it!
        # However my -nr option works with our way of declaring classes.
        lua ~/.vim/bundle/lua-david/lib/ltags/ltags -nr -filelist $tagfile.luaonly
        rm $tagfile.luaonly

        fix_file_prefix_for_tags_on_win32 tags
        mv tags lua.tags

        ctags --c++-kinds=+p --fields=+iaS --extra=+q -L $tagfile --exclude=*.lua
        ;;
    *)
        ctags -L $tagfile
        ;;
esac

fix_file_prefix_for_tags_on_win32 tags

if [ $cscope == "tagonly" ] ; then
	rm $tagfile

elif [ $cscope == "skip-cscope" ] ; then
    # Make empty cscope files so scripts expecting them don't barf.
    touch cscope.{in.,po.,}out

else
	case $filetype in
		python)
			# Requires the python package pycscope:
			#   pip install pycscope
			pycscope -i filelist
			;;
		*)
			# Build cscope database
			#	-b              Build the database only.
			#	-k              Kernel Mode - don't use /usr/include for #include files.
			#	-q              Build an inverted index for quick symbol seaching.
			# May want to consider these flags
			#	-m "lang"       Use lang for multi-lingual cscope.
			#	-R              Recurse directories for files.
			$cscope -b -q -k -i filelist

            # While cscope changed from cscope.out.$type to cscope.$type.out [1],
            # mlcscope will still complain that it cannot find cscope.out.in. Ignore
            # this error! It's not failing to find cscope.in.out, it's just stupid. If
            # you try to rename the files (mv cscope.in.out cscope.out.in), cscope will
            # stop working (you'll get errors about your database being invalid).
            # [1] https://bugzilla.redhat.com/show_bug.cgi?format=multiple&id=602738
            # TODO: cygwin replaced mlcscope with cscope. Does it still have this problem?
            ;;
    esac
fi

# }}}

fix_file_prefix_for_tags_on_win32 $tagfile

cd -
