#! /usr/bin/env python
# encoding: utf-8

# Define Rules
def add_custom_builder(env):
    # filename transformation
    suffix = '.REPLACE_after'
    src_suffix = '.REPLACE_before'

    # define the build method
    rule = 'REPLACE_build_program $SOURCE $TARGET'
    bld = Builder(action = rule,
                  suffix = suffix,
                  src_suffix = src_suffix)
    env.Append(BUILDERS = {'Custom' : bld})

    # define the targets (to autobuild by passing output filename)
    for target in Glob('*' + src_suffix):
        env.Custom(target)

    return env

# Create
env = add_custom_builder(Environment())

# Define Explicit Targets
Default(env.Custom('REPLACE_default_target'))

# For languages supported by scons, you can use Program instead:
#Program(
#    target = '.REPLACE_output',
#    source = ['.REPLACE_source']),
#    #LINKFLAGS = ['.REPLACE'],
#    #LIBS = ['.REPLACE']
#)
