#! /usr/bin/env python
# encoding: utf-8

# Define Rules
def add_custom_builder(env):
    # filename transformation
    suffix = '.REPLACE_after'
    src_suffix = '.REPLACE_before'

    # define the build method
    rule = 'REPLACE_build_program $SOURCE $TARGET'
    bld = Builder(action = rule,
                  suffix = suffix,
                  src_suffix = src_suffix)
    env.Append(BUILDERS = {'Custom' : bld})

    # define the targets (to autobuild by passing output filename)
    for target in Glob('*' + src_suffix):
        env.Custom(target)

# Create
env = Environment()
add_custom_builder(env)

# Define Explicit Targets
Default(env.Book('REPLACE_default_target' + src_suffix))
