## bashrc
# ~/.bashrc: executed by bash(1) for non-login shells.

DIR=~/data/settings/daveconfig/unix/terminal

# If we're using bash we're unix-like
source $DIR/unix.bashrc

# Used to use uname -o
# MinGW doesn't support uname -o
# -s is close (kernel name), so let's try that.
case "`uname -s`" in
MINGW*|CYGWIN*|MSYS_*)
    echo $DIR/cygwin.bashrc
	source $DIR/cygwin.bashrc
    ;;
Linux)
	source $DIR/ubuntu.bashrc
    ;;
Darwin)
    #
    ;;
*)
	echo "bashrc: Platform not supported"
    ;;
esac
