## bashrc
# ~/.bashrc: executed by bash(1) for non-login shells.

DIR=~/data/settings/daveconfig/unix/terminal

# If we're using bash we're unix-like
source $DIR/unix.bashrc

case "`uname -o`" in
Cygwin*)
	source $DIR/cygwin.bashrc
    ;;
Linux)
	source $DIR/ubuntu.bashrc
    ;;
*)
	echo "bashrc: Platform not supported"
    ;;
esac
