# Bash shortcuts
#
# My single bash_aliases file. I haven't tried separating each platform since I
# don't do that much on many platforms.

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# ls
alias ll='ls -l'
alias lh='ls -lh'
alias la='ls -A'
alias lll='ls -Ahl'
alias les='/usr/share/vim/vim73/macros/less.sh'
llw() {
    # easily find target of symlinks
    ls -l $(which $1)
}

# windows work-alike
alias cls='clear'
alias tracert='tracepath'


# python
#alias ipy='ipython'
alias ipy='screen -X title ipy ; ipython'

android_sdks=~/data/.android_devkit
alias and_export_sdk='export PATH=$PATH:$android_sdks/android-sdk-linux_86/tools:$android_sdks/android-sdk-linux_86/platform-tools'
alias and_go_sdk='cd $android_sdks/android-sdk-linux_86/platform-tools'
alias and_ndk_build='$android_sdks/android-ndk-r4b/ndk-build'

function init_skeleton {
    cp ../gitignore .gitignore
    git init
    git add .gitignore
    git ci -m'Initial commit'
    git add .
    git ci -m'Project skeleton'
}


# Quick way to view files in vim
function v { $* | view - ; }

function ge { gvim --remote-silent $* ; }
function move_and_link() {
    mv $1 $2
    ln -sv $2 $1
}

# Start serving the local directory as a website
alias webserve='python -m SimpleHTTPServer'


#################
# Location-specific section

# Home
alias butter='ssh flutterbutter.local'
alias mediabutter='ssh mediaserver@flutterbutter.local'



#################
# Platform-specific section


#################
# Linux

alias gogo='xdg-open'
# safer way to delete
alias trash='mv -t ~/.local/share/Trash/files --backup=t'
# aptitude
alias aptinstall='sudo aptitude install'
alias aptremove='sudo aptitude remove'
alias aptautoremove='sudo apt-get autoremove'   # no autoremove for aptitude
alias aptsearch='apt-cache search'
alias aptshow='apt-cache show'
alias aptwhichrepo='apt-cache policy'
alias aptpkglist='dpkg-query --list'


#################
# Mac (darwin)

#alias gogo='open'
# Ideally, I'd use $VIMRUNTIME. Didn't work last time I was on a mac.
#alias les='/Applications/MacVim.app/Contents/Resources/vim/runtime/macros/less.sh'
# safer way to delete
#alias trash='mv -t ~/.Trash --backup=t'


#################
# cygwin

#alias gogo='cygstart'
